variables:
  DOCKER_TLS_CERTDIR: ""
  PROJECT_NAME: "pf-ui-vue"
  GIT_CLEAN_FLAGS: "none"
  IMAGE_ENV: "platform"
  # IMAGE_ENV: "lichen"

default: 
  tags:
    - node
  image: node:16.16.0


stages: 
  - build
  - docker

build: 
  stage: build
  only:
    - tags
  script: 
    - npm config set registry https://maven-hz.rubikstack.com/repository/npm-public
    - npm install
    - npm run site
    - cp  ./Dockerfile ./site/dist
    - cp  ./nginx.conf ./site/dist
  # artifacts:
  #   paths:
  #     - /site/dist

docker: 
  stage:  docker
  image: docker:stable
  only:
    - tags  
  dependencies: 
    - build
  before_script:
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.txt
  script:
    - docker build --build-arg ARGVAL=prod.gogos -t $APPLICATION_IP/$IMAGE_ENV/$PROJECT_NAME:$CI_COMMIT_REF_SLUG ./site/dist
    - docker login --username=$HARBOR_USER_NAME --password-stdin < $HOME/.docker/config.txt $APPLICATION_IP
    - docker push $APPLICATION_IP/$IMAGE_ENV/$PROJECT_NAME:$CI_COMMIT_REF_SLUG
    - docker rmi $APPLICATION_IP/$IMAGE_ENV/$PROJECT_NAME:$CI_COMMIT_REF_SLUG

